<a href="https://colab.research.google.com/github/karsakami/Master-Math-by-Coding-in-Python/blob/main/Algebra%201/Lists_and_numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# int list
aList = [0,1,2,3,4,5]

# string list
sList = ['0', '1', '2', '3', '4', '5']

aList * 3

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [ ]:
# lets use numpy lists now
import numpy as np

In [ ]:
# convert int list to numpy array
aList_np = np.array(aList)

# lets see two classes 
print(type(aList))
print(type(aList_np))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# lets see difference
print(aList)
print(aList_np)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [ ]:
# now if we multiply this numpy list, there is not repeated, the values are multiplied
aList_np * 3

array([ 0,  3,  6,  9, 12, 15])

### Adding a int into list and numpy array

In [ ]:
print(aList_np + [3])
print(aList + [3])

[3 4 5 6 7 8]
[0, 1, 2, 3, 4, 5, 3]


## Exercise

In [ ]:
list1 = [3,4]
list2 = [2,['3', '4', '5']]
list3 = [5.2, 7.4, 5.5]
list4 = [2,3,4,[4,5,6]]

print("list element 0 is", list1[0], "and is of type", type(list1))
print("list element 1 is", list2[1], "and is of type", type(list2))
print("list element 2 is", list3[2], "and is of type", type(list3))
print("list element 3 is", list4[3], "and is of type", type(list4))

list element 0 is 3 and is of type <class 'list'>
list element 1 is ['3', '4', '5'] and is of type <class 'list'>
list element 2 is 5.5 and is of type <class 'list'>
list element 3 is [4, 5, 6] and is of type <class 'list'>
