<a href="https://colab.research.google.com/github/karsakami/Master-Math-by-Coding-in-Python/blob/main/Algebra%201/Matrixes_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MATRIXES WITH NUMPY**

In [ ]:
import numpy as np
import sympy as sym
from IPython.display import display,Math

In [ ]:
# Create and see a data type of object
A = np.array([[1,2], [5,3]])

type(A)

numpy.ndarray

In [ ]:
# Print it raw
print(A)

[[1 2]
 [5 3]]


In [ ]:
# Print it with sympy
sym.sympify(A)

[[1, 2], [5, 3]]

In [ ]:
# Creating a matrix of zeros
example = np.zeros([2,3])

In [ ]:
# Change a value in this matrix
example[0,2] = 4
example

array([[0., 0., 4.],
       [0., 0., 0.]])

In [ ]:
# Change another
example[0,1] = 3
example 

array([[0., 3., 4.],
       [0., 0., 0.]])

Lets change all values. The first for loop respond of rows, and second for columns. So the external loop goes, then it change three times value in matrix, and second loop goes on - second row. 

In [ ]:
for rowi in range(2):
  for coli in range(3):
    example[rowi,coli] = 2
  
example

array([[2., 2., 2.],
       [2., 2., 2.]])

### Calculation of all possible outcomes of a double coin toss with nested for loops. So we can deduct, that a external loop is getting executed, when a internal loop is finished. 

In [ ]:
for i in range(2):
  for j in range(2):
    print(i,j)

0 0
0 1
1 0
1 1


### **Matrix exercise.**

We have to solve a equation, all possible solutions.
A external for loop iterate over a rows, and internal over columns. 

In [ ]:
x, y = sym.symbols('x y')

fxy = (4+x) * (2-y)

yset = range(0,5)

matrx = np.zeros([len(yset), len(yset)])

for row in yset:
  for col in yset:
    matrx[row,col] = fxy.subs({x:row, y:col})

matrx

array([[  8.,   4.,   0.,  -4.,  -8.],
       [ 10.,   5.,   0.,  -5., -10.],
       [ 12.,   6.,   0.,  -6., -12.],
       [ 14.,   7.,   0.,  -7., -14.],
       [ 16.,   8.,   0.,  -8., -16.]])

# **Multiplication table**


In [ ]:
nums = range(1,11)

mult = np.zeros(( len(nums),len(nums) ))

for rowi in nums:
  for coli in nums:
    mult[rowi-1,coli-1] = rowi*coli

sym.sympify(mult)

[[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0], [2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0], [3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0, 27.0, 30.0], [4.0, 8.0, 12.0, 16.0, 20.0, 24.0, 28.0, 32.0, 36.0, 40.0], [5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0, 45.0, 50.0], [6.0, 12.0, 18.0, 24.0, 30.0, 36.0, 42.0, 48.0, 54.0, 60.0], [7.0, 14.0, 21.0, 28.0, 35.0, 42.0, 49.0, 56.0, 63.0, 70.0], [8.0, 16.0, 24.0, 32.0, 40.0, 48.0, 56.0, 64.0, 72.0, 80.0], [9.0, 18.0, 27.0, 36.0, 45.0, 54.0, 63.0, 72.0, 81.0, 90.0], [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0]]